spring.application.name=secureflow-api

spring.profiles.default=local

spring.datasource.url=${SECUREFLOW_DB_URL:jdbc:postgresql://localhost:5432/secureflow_db}
spring.datasource.username=${SECUREFLOW_DB_USERNAME:postgres}
spring.datasource.password=${SECUREFLOW_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

secureflow.jwt.secret=${SECUREFLOW_JWT_SECRET:}
secureflow.jwt.expiration-ms=${SECUREFLOW_JWT_EXPIRATION_MS:28800000}

server.port=${PORT:8080}
